spring:
  application:
    name: microservicio-1

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  level:
    org.springframework.web: INFO

server:
  port: 8081
  shutdown: immediate

jwt:
  secret: CeAIgCVfNlhJhRLNiwyTK6WMAYj6o7tTuf+0qMxN0fQ=
  expiration: 86400000