server.port=8080
spring.application.name=order-orchestrator
management.endpoints.web.exposure.include=health,info,metrics
springdoc.override-with-generic-response=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/**

services.inventory.base-url=${INVENTORY_BASE_URL}
services.payment.base-url=${PAYMENT_BASE_URL}
services.customer-validation.base-url=${CUSTOMER_VALIDATION_BASE_URL}
