server.port=8083
spring.application.name=customer-validation-service
management.endpoints.web.exposure.include=health,info,metrics
springdoc.override-with-generic-response=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/**